---
- name: install php apache
  yum:
    name: "{{ item }}"
  with_items:
    - php
    - php-mysql
    - httpd
    - phpmyadmin

# @see https://qiita.com/cognitom/items/57de72b739642041dcd5
- name: open port
  shell: >-
    c='/etc/httpd/conf.d/phpMyAdmin.conf' &&
    k='<Directory \/usr\/share\/phpMyAdmin\/>' &&
    s='Allow from ::1' &&
    r='     Allow from 10.0.2.2' &&
    cp -ip $c $c.backup &&
    awk "/$k/{f=1} f==1&&/$s/{sub(/$s/,\"$s\n$r\"); f=0} 1" $c > /tmp/phpMyAdmin.conf &&
    mv /tmp/phpMyAdmin.conf $c &&
    k='<Directory \/usr\/share\/phpMyAdmin\/setup\/>' &&
    awk "/$k/{f=1} f==1&&/$s/{sub(/$s/,\"$s\n$r\"); f=0} 1" $c > /tmp/phpMyAdmin.conf &&
    mv /tmp/phpMyAdmin.conf $c
  args:
    creates: /tmp/phpMyAdmin.conf
  notify:
    - restart apache
  sudo: yes

- name: set start apache automaticaly
  service:
    name: httpd
    state: started
    enabled: yes
